Repository Activiti/activiti-modeling-app, pull requests merged in 2019-06, with the labels that each got.

#171 [APM-1071] Use HashLocationStrategy in the application
  e2e/protractor.conf.js
  e2e/tests/process/create-process.e2e.ts
  e2e/tests/process/delete-process.e2e.ts
  projects/ama-testing/src/e2e/api/acm/acm-backend.ts
  projects/ama-testing/src/e2e/pages/common/generic.page.ts
  projects/ama-testing/src/e2e/pages/login-aps.page.ts
  src/app.config.json
  src/app/app.module.ts
Labels: do not merge

#176 [APM-1017] Process xml editor fix
  src/app/process-editor/components/process-editor/process-editor.component.ts
Labels: needs rebase

#180 [APM-1080] Create entity small fix
  projects/ama-sdk/src/lib/helpers/components/entity-dialog/entity-dialog.component.spec.ts
  projects/ama-sdk/src/lib/helpers/components/entity-dialog/entity-dialog.component.ts
Labels: next to merge

#174 [APM-1072] Increase page size if project is not displayed on first page
  e2e/tests/connector/list-connectors.e2e.ts
  package-lock.json
  projects/ama-testing/src/e2e/pages/dashboard.page.ts
  projects/ama-testing/src/e2e/pages/pagination.component.ts
  src/app/dashboard/components/projects-list/projects-list.component.ts
Labels: do not merge

#183 APM-1088 fix release list and rebase
  src/app/dashboard/components/releases-list/releases-list.component.html
  src/app/dashboard/components/releases-list/releases-list.component.scss
  src/app/dashboard/components/releases-list/releases-list.component.ts
Labels: next to merge

#184 Provide proper content extension and name, when using the API for creating models
  package-lock.json
  projects/ama-testing/src/e2e/api/acm/acm-crud.ts
  projects/ama-testing/src/e2e/api/acm/models/connector.ts
  projects/ama-testing/src/e2e/api/acm/models/data.ts
  projects/ama-testing/src/e2e/api/acm/models/decision-table.ts
  projects/ama-testing/src/e2e/api/acm/models/form.ts
  projects/ama-testing/src/e2e/api/acm/models/process.ts
  projects/ama-testing/src/e2e/api/acm/models/ui.ts
  projects/ama-testing/src/e2e/api/api.interfaces.ts
Labels: next to merge

#187 ADF 3.3.0
  package-lock.json
  package.json
  projects/ama-sdk/package.json
Labels: next to merge

#185 [APM-1052] User friendly validation messages
  projects/ama-sdk/src/lib/helpers/common.ts
  projects/ama-sdk/src/lib/helpers/components/entity-dialog/entity-dialog.component.html
  projects/ama-sdk/src/lib/helpers/components/entity-dialog/entity-dialog.component.ts
  projects/ama-sdk/src/lib/interfaces/model-creator.interface.ts
  resources/i18n/en.json
  src/app/connector-editor/extension/connector-creator.extension.ts
  src/app/dashboard/components/dahboard-navigation/dashboard-navigation.component.ts
  src/app/dashboard/components/projects-list/projects-list.component.ts
Labels: next version

#191 APM-1082 empty name error added
  resources/i18n/en.json
  src/app/process-editor/store/process-editor.effects.ts
Labels: next version

#192 [apm-1081] fixed process editor spinner issue
  projects/ama-sdk/src/lib/helpers/public_api.ts
  src/app/app.module.ts
  src/app/common/helpers/services/error-handler.service.ts
  src/app/common/helpers/services/error.service.ts
  src/app/process-editor/store/process-editor.actions.ts
  src/app/process-editor/store/process-editor.effects.spec.ts
  src/app/process-editor/store/process-editor.effects.ts
  src/app/process-editor/store/process-editor.reducer.spec.ts
  src/app/process-editor/store/process-editor.reducer.ts
Labels: next to merge

#194 [APM-1023] Project release e2e tests
  projects/ama-testing/src/e2e/api/acm/project.ts
  projects/ama-testing/src/e2e/api/api.interfaces.ts
  projects/ama-testing/src/e2e/pages/dashboard.page.ts
  projects/ama-testing/src/e2e/pages/snackbar.ts
  src/app/dashboard/components/projects-list/projects-list.component.html
  src/app/dashboard/components/releases-list/releases-list.component.html
Labels: do not merge

#195 [APM-1094] Add standAlone property to schema and FormDefinition
  projects/ama-sdk/src/lib/api/types.ts
  projects/ama-sdk/src/lib/schemas/form.schema.ts
Labels: needs rebase
